node_prefix: "server-"
node_details_update_interval_in_seconds: 1
etcd_cluster_hosts: "http://10.0.0.2:2379,http://10.0.0.3:2379,http://10.0.0.4:2379"
etcd_cluster_dial_timeout_in_seconds: 5
etcd_cluster_request_timeout_in_seconds: 10
etcd_cluster_election_key: "/manager-service-master-election/"
db_driver: "postgres"
db_host: "10.0.0.5"
db_port: 5432
db_name: "ne"
db_username: "un"
db_password: "pass"
db_connection_timeout: 50
db_max_open_connections: 50
db_max_idle_connections: 50
db_max_connection_lifetime: 0
max_shard_size: 1
rabbitmq_username: "guest"
rabbitmq_password: "guest"
rabbitmq_host: "10.0.0.6"
rabbitmq_port: 5672
api_port: 8080
worker_queue_name: "worker-queue"
done_queue_name: "done-queue"